### PR TITLE
Added changes in DeskKit

### PR DESCRIPTION
**Pull request by artemch**
Fixed ARC supporting (removed autorelease method call) for NSViewController+IDPExtension and NSNib+IDPExtension.

Added NSColor extension.
Added new methods to NSViewController, NSWindowController and NSView.
Some cleanup.

### CODE REVIEW

**Comment by trimmurrti** [comment]
- (instancetype)controllerWithDefaultNib;

Rename to controller and document, that it uses default nib and rules of the default nib
Make the implementation and the interface methods have the same outputs defaulting to instancetype

**Comment by trimmurrti** [comment]
Update OSX test workspace

**Comment by artemch** [comment]
Update DeskKit. Removed unused extensions and methods.
Fixed IDPKit.podspec dependency for DeskKit.
Update IDPKit.podspec version  to 0.1.2.
Added new macros to IDPUtilityMacros.

**Comment by trimmurrti** [comment]
Please, fix the formatting in math formulas (what I've found, but the list is not complete):
- (CGFloat)luminosityDifference:(NSColor*)otherColor 
- (NSColor *)averageColor

There should be a whitespace before return, if return is not the only statement in visibility scope (e.g. - (CGImageRef)CGImage)

Local variables should be nullified:
- (CGImageRef)CGImage
- (NSImage *)imageFromView -> rename into imageRepresentation

localPointFromEvent: -> pointWithEvent

IDPKitTests.xccheckout -> do we need it in the repo?

**Comment by artemch** [comment]
Update according to remarks.

**Pull request merged**
